stages: 
  - test

postman_tests:
  stage: test
  image: 
    name: postman/newman_alpine33
    entrypoint: [""]
  script:
    - newman --version
    - newman run Passing Postman collection.postman_collection.json
